services:
  lambda:
    # entrypoint: python -c "from linkedin_post_explorer.aws_lambda_handler import handler; handler(None, None)"
    command: [ "sqlite_vec_playground.handler" ]
    build:
      context: .
      dockerfile: Dockerfile
    image: linkedin-lambda # assigns a name to the built image
    platform: linux/amd64
    # volumes:
    #   - ./src/linkedin_post_explorer/:/function/linkedin_post_explorer
    ports:
      - "9000:8080"
    environment:
      AWS_LAMBDA_FUNCTION_TIMEOUT: 900
      AWS_LAMBDA_FUNCTION_MEMORY_SIZE: 128
      BUCKET_NAME: linkedin-post-explorer-data

# could mock S3 with localstack/moto; or just provide creds
